### PR TITLE
Make Bluetooth support configurable

### PR DESCRIPTION
**Pull request by sebres**
TclIOCP library is actually a good replacement for default tcl-socket facility. But at the moment it is statically linked to `bthprops.lib` which could dependently where it was build add a fixed dependency to `bthprops.cpl`, so it may be hardly possible to use this module on Windows systems without Bluetooth support by default or with different Windows Bluetooth library stack (e. g. several Windows Server versions).

This can be solved by introducing dynamical liking for Bluetooth library (LoadLibrary/FreeLibrary and GetProcAddress for Bluetooth-API), but if Bluetooth support is not required at all (for instance only IOCP-sockets are interesting) this can also be simply configurable option (to the build time).

This PR adds a new parameter `--enable-bluetooth` (default yes) to enable/disable Bluetooth support (and bthprops.cpl dependency of the library).

Result of build with and without bluetooth support:
```diff
 $ ntldd iocp*.dll
-        bthprops.cpl => bthprops.cpl
         KERNEL32.dll => KERNEL32.dll
         msvcrt.dll => msvcrt.dll
         RPCRT4.dll => RPCRT4.dll
         WS2_32.dll => WS2_32.dll
```

Specifying `--enable-bluetooth=lazy` creates a new command `iocp::bt` loading bluetooth facilities on demand.

### CODE REVIEW

**Comment by apnadkarni** [comment]
Thanks Sergey. Would delay loading also be another possible solution?

**Comment by sebres** [comment]
You're welcome, Ashok.

I don't really know whether a lazy loading would help here, since an initialization (BT_ModuleInitialize) is made directly in Iocp_Init. as well as whether it is supported using auto-make tools (mingw) and using VS-compiler (nmake).
By the way, this is rather an "artificial" PR (how I solved this quick and dirty), so at the moment I changed only auto-make build which I prefer, so makefile.vc or rules.vc are still untouched in this PR (so if it gets merged as is, there will be no bluetooth support for VS build possible).

**Comment by apnadkarni** [comment]
I have committed code to dynamically load bluetooth calls through getprocaddr as I want only a single Windows binary and not dependent on compile time configuration. Now the question is - how does one test this? I have only one system so I'm a little wary of deleting system DLL's from it for testing purposes and suspect even if I delete it, Windows will replace it from the cache right away. Do you have a bluetooth-less server you can try it on?

 I was actually not even aware that the server editions were missing some "system" dlls so thanks for letting me know else I would have been wondering why it was not loading on some systems.

**Comment by apnadkarni** [comment]
Sergey, please hold off on testing. Need to fix something.

**Comment by apnadkarni** [comment]
Broken dll path fixed. Can be tested now.

**Comment by sebres** [comment]
> Do you have a bluetooth-less server you can try it on?

Sure, I'll try to test it.

> I want only a single Windows binary and not dependent on compile time configuration.

Clear, although I think the option to disable bluetooth is anyway helpful (for people/projects don't need it at all).

**Comment by sebres** [comment]
Test is successful. It works, just...

Would it not be better to load this if bluetooth is really required, e. g. to call `BT_InitAPI` on demand by first usage or to make it extra loadable in module (together with `BT_ModuleInitialize`) within own initializer proc, like `load tcliocp.dll iocpbt`, so the library bthprops.cpl, the namespace `iocp::bt` etc is loaded only if it is really needed?

**Comment by sebres** [comment]
I'll try to implement it in this PR... WiP.

BTW, `Iocp_DoOnce` implements wait (IOCP_INITSTATE_IN_PROGRESS) with a busy loop (1ms to sleep is a bit ugly) what may be too heavy, for example if large MT-application doing socket initialization directly on start from scratch.
Why don't use mutex (critical section) instead?

**Comment by sebres** [comment]
PR is changed now:
- it is backwards compatible, option `--enable-bluetooth` is yes by default (definition IOCP_ENABLE_BLUETOOTH is optional);
- configuring `--enable-bluetooth=no` or `--disable-bluetooth` completely disables bluetooth functionality (and then there will be no `iocp::bt` namespace)
- configuring `--enable-bluetooth=lazy` creates a build with loading BT on demand - a new command `iocp::bt` loading bluetooth facilities (`iocp::bt` namespace).

**Comment by apnadkarni** [comment]
Thanks, I will take a look tomorrow. Today's open source time is dedicated to bluetooth test suite. I just discovered yesterday to my horror that I had released prior versions without a single bluetooth test (only based on my manual testing for my blog). I don't know how I overlooked such a basic thing for release!

**Comment by apnadkarni** [comment]
Having taken a quick look, I'm not quite ready to pick this up as is, need to think through it a bit. Will come back with thoughts in a couple of days.

**Comment by sebres** [comment]
NP.
My first idea was to make the lazy loading really on demand (by first usage), but `iocp::bt` namespace has too many commands (not `bt::socket` only), so one have to mockup a lot of commands with auto-loading, and core-tcl does not have auto-loading mechanisms for namespaces (tclIndex) and loading twice (i. e. `load lib a; load lib b`) is also prohibited at the moment - one binary can contain only one package, so I made the lazy loading as is, with loader command `iocp::bt`.

**Comment by apnadkarni** [comment]
I have made the following changes in the master branch.
- The bluetooth API table is only populated on a "package require iocp_bt" (so lazy loading always even if bluetooth enabled)
- --disable-bluetooth will eliminate all bluetooth from install including the tcl files, and package require iocp_bt will not find the package. There is no "lazy" option, only --enable-bluetooth={yes,no}.
- Similarly, the OPTS=nobt option in the nmake build.

I think that meets your original requirements. I have not used mutexes. The original reason for busy loop was based on recommendation (I think from MSDN or maybe duffy's Windows Concurrent programming book) of this idiom over mutexes for performance reasons. Mutexes require kernel transistion for the common case which is far more expensive than the busy loop. Critical sections do not require kernel transitions but they themselves need init which brings us back to square one. I've preferred to leave it as it was except the BT module now does its own init for lazy loading.

BTW, was there any reason other than slightly smaller code size for --disable-bluetooth? As a rule I hesitate to add configuration option because of the additional testing burden at release time to test all configurations. In any case, it is added.

If you are ok with above, I will close the pull request. Thanks for your suggestions.

**Comment by sebres** [comment]
Good, thank you! I'll take a look if I get a free minute.

> Mutexes require kernel transistion for the common case which is far more expensive than the busy loop.

No. It were a nonsense if it would be so.
Note that sleep(1) in cycle would cause a lot of context-switches, which is noncomparable much more expensive than a single mutex lock (without cycle).
And costs of such wait are not linear (grows with number of workers entering the busy "lock" loop at once).

Also if your intention is to backport the module for core-tcl at some point (I think, I heart that from you), this will be definitely an issue, once TCT begins to review your code.

But OK, it is just an initialization phase (so would affect only if several workers loading package by start at once). Although in my case it may be a lot of threads (just no idea whether they will reach the lock simultaneously). 
Never mind, I'll simply hold it in my fork with the mutex.

> was there any reason other than slightly smaller code size for --disable-bluetooth?

Well, basically 3 reasons:
- it should work on server without bluetooth (if it is not needed at all); sure, this is conditionally done by you now with loading on demand, but it has previously always loaded bt-cpl (and crated bluetooth namespace commands) :)
- if only sockets required at all, providing a bluetooth functionality in same module is a bit ugly (at least unpreferable in enterprise);
I know the reasons for combining to single module (you need common iocp-handling used for both things), but one could build it more modularly anyway. Or even simply disable stuff one does not expect (like I did).
- and last but not least, it "violate" 1st rule of \*nix philosophy "Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features". 
I know we're in Windows world here, but tcl is for any platform, so...

Thus let's close for now (I can reopen if I'd find something bothering me).

**Pull request closed without merging**
